- pyef/analysis.py
> add comment

- pyef/ExampleUsage.py
- pyef/analysis.py
> Add atom indexing for Efield Coordinates

- pyef/ExampleUsage.py
- pyef/analysis.py
> created idxBondedAtom function to avoid molsimplify dependency

- environment.yml
- pyef/analysis.py
- pyef/cli.py
- pyef/manage.py
Changed the CLI so that rather than having to input the paths through the command line, the user can now submit a list of paths through a single file, which will be prompted for when pyEF is run.
> Added a job file for batch calculations

- pyef/analysis.py
> Fixed frame issue in fixprepData

- pyef/analysis.py
> Fixprep data

- pyef/cli.py
Updated the pyEF CLI to be more aesthetic. Also added a ASCII logo.
> Improved the CLI welcome

- pyef/analysis.py
> Removed Charge calculation dependence in Efield Calculation

- pyef/analysis.py
- pyef/cli.py
- pyef/manage.py
- pyef/resources/settings.ini
- pyef/run.py
Fixed a number of bugs that were preventing the code from being run cleanly as a package.
> Fixed a number of bugs

- pyef/analysis.py
> Added Shaik Efield Calc Functioanlity

- pyef/analysis.py
> Add functionality to change dielectric near bonds

- pyef/analysis.py
> Efieldcompatwith mm

- pyef/analysis.py
> Fixed partial charge function

- pyef/analysis.py
> Added fix to ensure that Fe with ECP molden files are in correct format

- environment.yml
- pyef/analysis.py
- pyef/cli.py
- pyef/manage.py
- pyef/resources/settings.ini
- pyef/run.py
PyEF has been updated to work on both Gibraltar and SuperCloud.
> Updated to work on supercloud

- pyef/analysis.py
> Fixed ESP function and added method of quantifying residue charges

- pyef/analysis.py
> Troubleshooting

- pyef/analysis.py
> Added function to calc ESP for larger system with multipole method

- pyef/PartialCharges
- pyef/analysis.py
> New method to directly calculate electric fields with pyscf

- pyef/analysis.py
- pyef/partialcharges.py
> fixed hirshfeld* to hirshfeld-I for Efield function

- pyef/analysis.py
> Added docstrings to all functions

- pyef/analysis.py
> Simplified ESP units to volts

- pyef/analysis.py
> Re-centered Dipoles

- pyef/analysis.py
- pyef/geometry.py
> Fixed dipole multipole functionality

- pyef/analysis.py
> Fixed atm folder in multipole hirshfeld I

- pyef/analysis.py
- pyef/geometry.py
> Made Centroid and fixed the metal handling for Pd

- pyef/analysis.py
- pyef/geometry.py
> Restructed ESP calculations for simplicity and fixed bugs

- pyef/analysis.py
> Fully functioning atom-wise Efield contirbutionsgit branch

- pyef/analysis.py
- pyef/geometry.py
> working visualization

- pyef/analysis.py
> Fixed ECP correction

- pyef/analysis.py
> Electrostatic stabilization now working!
